image:
  file: .gitpod.Dockerfile
tasks:
- before: >
    source ~/.bashrc
  init: >
    flutter create --project-name lanchat .
vscode:
  extensions:
    - Dart-Code.dart-code
    - Dart-Code.flutter
    - matklad.rust-analyzer
ports:
  - port: 6080
