image:
  file: .gitpod.Dockerfile
tasks:
- before: >
    source ~/.bashrc
  init: >
    flutter upgrade && 
    flutter update-packages --force-upgrade &&
vscode:
  extensions:
    - Dart-Code.dart-code@3.5.1:W6zqgIED1gxtkBH/pbfGXA==
    - Dart-Code.flutter@3.5.1:0FyuzXye7dV19PNst3+Llg==
